FROM {{{from}}}

# Configure apt
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN yarn global add rde

WORKDIR {{{workDir}}}

COPY .cache/package-cache.json template/.npmrc* template/.yarnrc* {{{workDir}}}/
RUN mv package-cache.json package.json

{{!cache node-modules}}
RUN yarn
