FROM {{{from}}}

WORKDIR {{{workDir}}}

RUN npm i -g rde

{{#isApp}}
COPY .cache/package.json {{{workDir}}}/package.json
{{/isApp}}
{{^isApp}}
COPY template/package.json {{{workDir}}}/package.json
{{/isApp}}

{{!cache node-modules}}
RUN npm i
